# -*- coding: utf-8 -*-
"""Quiz#008

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JDHiPxXsaw2VH4awtxulVwH1hmeayZ-C
"""

def BigNeighbour(list1):
  d=0
  max=0
  for i in range(len(list1)-1):
    d=abs(list1[i] - list1[i+1])
    if d>max:
      max=d
    d=0
  return max
print(BigNeighbour([1,2,3,5,6,7]))
print(BigNeighbour([0,5,6,10]))
print(BigNeighbour([73,74,174,76,78,79]))