# -*- coding: utf-8 -*-
"""Quiz#013

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BZYuRPXy71IPjCvSOSET7O_PSFY6fkA8
"""

def total(items=[], price=[]):
  food = ["pasta", "bread", "pizza"]
  electronics = ["ipad", "tv", "pc"]
  Liqueur = ["wine", "vodka", "beer"]
  total=0
  for i in range(len(price)):
    if items[i] in food:
      total += price[i]*1.1
    elif items[i] in electronics:
      total += price[i]*1.15
    else:
     total += price[i]*1.2
  return total

print(total(["bread","beer","ipad"],[300, 800, 30000]))