# -*- coding: utf-8 -*-
"""Quiz#011

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wXr5pNdmICv1ohQOzXKSTIGQdnjVINM0
"""

def SameFirstLast(list1=[]):
  if len(list1)>1 and list1[0]==list1[-1]:
    statement = True
  else:
    statement = False
  return statement
print(SameFirstLast([1,2,3]))
print(SameFirstLast([1,2,3,1]))
print(SameFirstLast([1,2,1]))