# -*- coding: utf-8 -*-
"""Quiz#013

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BZYuRPXy71IPjCvSOSET7O_PSFY6fkA8
"""

def total(items=[], price=[]):
  food = ["pasta", "bread", "pizza"]
  electronics = ["ipad", "tv", "pc"]
  liqueur = ["wine", "vodka", "beer"]
  total=0
  for i in range(len(price)):
    if items[i] in food:
      total += price[i]*1.1
    elif items[i] in electronics:
      total += price[i]*1.15
    elif items[i] in liqueur:
      total += price[i]*1.2
    else:
      print("The item is not in the database")
      print("Is the item food, electronics or linquer?")
      answer=input("Write 'f' for food, 'e' for electronics and 'l' for linquer: ")
      if answer=="f":
        food.append(items[i])
        total += price[i]*1.1
      elif answer=="e":
        electronics.append(items[i])
        total += price[i]*1.15
      elif answer=="l":
        liqueur.append(items[i])
        total += price[i]*1.2  
  return total

print(total(["apple","beer","ipad"],[300, 800, 30000]))