# -*- coding: utf-8 -*-
"""Quiz#008

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JDHiPxXsaw2VH4awtxulVwH1hmeayZ-C
"""

def maxAbs(list1=[]):
    nlist=[]
    for i in range(len(list1)):
        nlist.append(abs(list1[i]))
    for i in range(len(nlist)):
        if i==0:
            maximum = nlist[i]
        if nlist[i]>maximum:
            maximum=nlist[i]
    return maximum
    
print(maxAbs(list1=[-4, 5, 6, -7]))
print(maxAbs(list1=[-1, 0, 1]))
print(maxAbs(list1=[-100, 0, 3, -200]))